// Plantbase — előre generált seed adat (~30 realisztikus növény).
// A mezőnevek a `products` séma szerint (snake_case). A seedeléshez lásd `seed.ts`.
// Ár HUF-ban. sale_price = null, ha nincs akció. stock = 0 -> nincs raktáron.

export type PlantSeed = {
  name: string
  latin_name: string
  category: string // szobanövény | kerti | pozsgás | kaktusz | fűszer | fa-cserje | lógó | virágzó
  location: string // beltéri | kültéri | mindkettő
  price: number
  sale_price: number | null
  stock: number
  light: string // árnyék | alacsony | közepes | erős | direkt nap
  watering: string // ritka | közepes | gyakori | állandóan nedves
  difficulty: string // kezdő | haladó | profi
  current_height_cm: number
  max_height_cm: number
  current_pot_cm: number
  pet_safe: boolean
  kid_safe: boolean
  air_purifying: boolean
  rating: number
  reviews_count: number
  description: string
}

export const plants: PlantSeed[] = [
  { name: 'Kentia pálma', latin_name: 'Howea forsteriana', category: 'szobanövény', location: 'beltéri', price: 18900, sale_price: 15900, stock: 7, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 90, max_height_cm: 250, current_pot_cm: 21, pet_safe: true, kid_safe: true, air_purifying: true, rating: 4.7, reviews_count: 134, description: 'Elegáns, könnyen tartható szobapálma, jól tűri a közepes fényt.' },
  { name: 'Hegedűfügefa', latin_name: 'Ficus lyrata', category: 'szobanövény', location: 'beltéri', price: 12900, sale_price: null, stock: 12, light: 'erős', watering: 'közepes', difficulty: 'haladó', current_height_cm: 70, max_height_cm: 200, current_pot_cm: 19, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.3, reviews_count: 98, description: 'Látványos, nagy levelű dísznövény, erős, szórt fényt igényel.' },
  { name: 'Vitorlavirág', latin_name: 'Spathiphyllum wallisii', category: 'virágzó', location: 'beltéri', price: 4500, sale_price: 3600, stock: 25, light: 'alacsony', watering: 'gyakori', difficulty: 'kezdő', current_height_cm: 35, max_height_cm: 60, current_pot_cm: 13, pet_safe: false, kid_safe: false, air_purifying: true, rating: 4.6, reviews_count: 210, description: 'Árnyéktűrő, fehéren virágzó klasszikus, kiváló légtisztító.' },
  { name: 'Sárkányfa', latin_name: 'Dracaena marginata', category: 'szobanövény', location: 'beltéri', price: 6900, sale_price: null, stock: 18, light: 'alacsony', watering: 'ritka', difficulty: 'kezdő', current_height_cm: 80, max_height_cm: 180, current_pot_cm: 17, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.4, reviews_count: 76, description: 'Karcsú, keskeny levelű, igénytelen szobanövény kezdőknek.' },
  { name: 'Aranyos pothos', latin_name: 'Epipremnum aureum', category: 'lógó', location: 'beltéri', price: 3200, sale_price: null, stock: 40, light: 'alacsony', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 25, max_height_cm: 150, current_pot_cm: 12, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.8, reviews_count: 312, description: 'Szinte elpusztíthatatlan, gyorsan növő futónövény polcra, szekrény tetejére.' },
  { name: 'Szobafilodendron', latin_name: 'Philodendron hederaceum', category: 'lógó', location: 'beltéri', price: 3900, sale_price: null, stock: 22, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 30, max_height_cm: 120, current_pot_cm: 12, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.7, reviews_count: 145, description: 'Szív alakú leveles, hálás futónövény, alacsony fényt is tűr.' },
  { name: 'Lyukaslevelű filodendron', latin_name: 'Monstera deliciosa', category: 'szobanövény', location: 'beltéri', price: 8900, sale_price: 6900, stock: 15, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 55, max_height_cm: 250, current_pot_cm: 17, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.9, reviews_count: 287, description: 'A népszerű Monstera, hasított leveleivel azonnali dzsungelhangulat.' },
  { name: 'Anyósnyelv', latin_name: 'Dracaena trifasciata', category: 'szobanövény', location: 'beltéri', price: 4900, sale_price: null, stock: 30, light: 'alacsony', watering: 'ritka', difficulty: 'kezdő', current_height_cm: 45, max_height_cm: 90, current_pot_cm: 14, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.8, reviews_count: 198, description: 'A legkönnyebb növény: ritka öntözés, bármilyen fény, erős légtisztító.' },
  { name: 'Zamiokulkász', latin_name: 'Zamioculcas zamiifolia', category: 'szobanövény', location: 'beltéri', price: 6500, sale_price: null, stock: 0, light: 'alacsony', watering: 'ritka', difficulty: 'kezdő', current_height_cm: 40, max_height_cm: 90, current_pot_cm: 15, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.7, reviews_count: 121, description: 'Fényes, viaszos levelű, szárazságtűrő iroda- és lakásnövény.' },
  { name: 'Aloe vera', latin_name: 'Aloe vera', category: 'pozsgás', location: 'mindkettő', price: 2500, sale_price: null, stock: 35, light: 'erős', watering: 'ritka', difficulty: 'kezdő', current_height_cm: 25, max_height_cm: 60, current_pot_cm: 12, pet_safe: false, kid_safe: true, air_purifying: false, rating: 4.5, reviews_count: 160, description: 'Hasznos, gyógyító nedvű pozsgás, sok napfénnyel a legszebb.' },
  { name: 'Pénzfa', latin_name: 'Crassula ovata', category: 'pozsgás', location: 'beltéri', price: 2900, sale_price: 2200, stock: 28, light: 'erős', watering: 'ritka', difficulty: 'kezdő', current_height_cm: 20, max_height_cm: 90, current_pot_cm: 12, pet_safe: false, kid_safe: true, air_purifying: false, rating: 4.6, reviews_count: 88, description: 'Vastag, kerek levelű pozsgás cserje, a szerencse jelképe.' },
  { name: 'Echeveria', latin_name: 'Echeveria elegans', category: 'pozsgás', location: 'beltéri', price: 1500, sale_price: null, stock: 50, light: 'direkt nap', watering: 'ritka', difficulty: 'kezdő', current_height_cm: 8, max_height_cm: 15, current_pot_cm: 8, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.4, reviews_count: 64, description: 'Rózsa alakú, kékeszöld pozsgás, ablakpárkányra tökéletes.' },
  { name: 'Aranylabda kaktusz', latin_name: 'Echinocactus grusonii', category: 'kaktusz', location: 'beltéri', price: 3500, sale_price: null, stock: 16, light: 'direkt nap', watering: 'ritka', difficulty: 'kezdő', current_height_cm: 15, max_height_cm: 80, current_pot_cm: 13, pet_safe: true, kid_safe: false, air_purifying: false, rating: 4.5, reviews_count: 42, description: 'Gömb alakú, tüskés gyűjtői kaktusz, nagyon kevés vízzel.' },
  { name: 'Karácsonyi kaktusz', latin_name: 'Schlumbergera truncata', category: 'kaktusz', location: 'beltéri', price: 2800, sale_price: null, stock: 20, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 20, max_height_cm: 40, current_pot_cm: 12, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.6, reviews_count: 73, description: 'Télen látványosan virágzó lógó kaktusz, állatbarát.' },
  { name: 'Bazsalikom', latin_name: 'Ocimum basilicum', category: 'fűszer', location: 'mindkettő', price: 990, sale_price: null, stock: 60, light: 'erős', watering: 'gyakori', difficulty: 'kezdő', current_height_cm: 18, max_height_cm: 45, current_pot_cm: 11, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.2, reviews_count: 51, description: 'Friss konyhai fűszer, napos ablakban folyamatosan szedhető.' },
  { name: 'Rozmaring', latin_name: 'Salvia rosmarinus', category: 'fűszer', location: 'mindkettő', price: 1490, sale_price: null, stock: 33, light: 'direkt nap', watering: 'ritka', difficulty: 'haladó', current_height_cm: 25, max_height_cm: 120, current_pot_cm: 13, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.3, reviews_count: 47, description: 'Illatos, örökzöld konyhai cserje, sok napot és kevés vizet kér.' },
  { name: 'Levendula', latin_name: 'Lavandula angustifolia', category: 'virágzó', location: 'kültéri', price: 1990, sale_price: 1590, stock: 45, light: 'direkt nap', watering: 'ritka', difficulty: 'haladó', current_height_cm: 25, max_height_cm: 70, current_pot_cm: 14, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.7, reviews_count: 156, description: 'Illatos, lila virágú kerti félcserje, méhbarát és szárazságtűrő.' },
  { name: 'Borostyán', latin_name: 'Hedera helix', category: 'lógó', location: 'mindkettő', price: 2200, sale_price: null, stock: 38, light: 'alacsony', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 20, max_height_cm: 200, current_pot_cm: 12, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.4, reviews_count: 69, description: 'Örökzöld kúszónövény bel- és kültérre, gyorsan benövi a felületet.' },
  { name: 'Boston páfrány', latin_name: 'Nephrolepis exaltata', category: 'szobanövény', location: 'beltéri', price: 3400, sale_price: null, stock: 19, light: 'közepes', watering: 'gyakori', difficulty: 'haladó', current_height_cm: 35, max_height_cm: 70, current_pot_cm: 15, pet_safe: true, kid_safe: true, air_purifying: true, rating: 4.2, reviews_count: 58, description: 'Dús, lecsüngő páfrány, párás környezetet és rendszeres vizet kér.' },
  { name: 'Calathea', latin_name: 'Calathea orbifolia', category: 'szobanövény', location: 'beltéri', price: 5900, sale_price: null, stock: 11, light: 'közepes', watering: 'gyakori', difficulty: 'profi', current_height_cm: 30, max_height_cm: 90, current_pot_cm: 15, pet_safe: true, kid_safe: true, air_purifying: true, rating: 4.1, reviews_count: 64, description: 'Mintás, ezüstcsíkos levelek; igényes a páratartalomra és a vízminőségre.' },
  { name: 'Lepkeorchidea', latin_name: 'Phalaenopsis', category: 'virágzó', location: 'beltéri', price: 4200, sale_price: 3200, stock: 27, light: 'közepes', watering: 'ritka', difficulty: 'haladó', current_height_cm: 45, max_height_cm: 70, current_pot_cm: 12, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.5, reviews_count: 188, description: 'Hetekig nyíló, elegáns szobaorchidea, állatbarát ajándéknövény.' },
  { name: 'Királybegónia', latin_name: 'Begonia rex', category: 'virágzó', location: 'beltéri', price: 3100, sale_price: null, stock: 14, light: 'közepes', watering: 'közepes', difficulty: 'haladó', current_height_cm: 22, max_height_cm: 40, current_pot_cm: 13, pet_safe: false, kid_safe: true, air_purifying: false, rating: 4.0, reviews_count: 37, description: 'Színes, mintás levélzetéért tartott dísznövény, szórt fényben a legszebb.' },
  { name: 'Muskátli', latin_name: 'Pelargonium', category: 'virágzó', location: 'kültéri', price: 1290, sale_price: null, stock: 70, light: 'direkt nap', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 20, max_height_cm: 50, current_pot_cm: 12, pet_safe: false, kid_safe: true, air_purifying: false, rating: 4.3, reviews_count: 92, description: 'Klasszikus balkonvirág, egész nyáron folyamatosan virágzik.' },
  { name: 'Japán juhar', latin_name: 'Acer palmatum', category: 'fa-cserje', location: 'kültéri', price: 12500, sale_price: null, stock: 6, light: 'közepes', watering: 'közepes', difficulty: 'profi', current_height_cm: 60, max_height_cm: 400, current_pot_cm: 23, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.8, reviews_count: 41, description: 'Finom lombú, ősszel tűzpirosan színeződő díszfa, félárnyékot kedvel.' },
  { name: 'Olajfa', latin_name: 'Olea europaea', category: 'fa-cserje', location: 'mindkettő', price: 15900, sale_price: 12900, stock: 9, light: 'direkt nap', watering: 'ritka', difficulty: 'haladó', current_height_cm: 80, max_height_cm: 300, current_pot_cm: 24, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.6, reviews_count: 53, description: 'Mediterrán, ezüstös lombú fa terasra; sok nap, kevés víz.' },
  { name: 'Citromfa', latin_name: 'Citrus limon', category: 'fa-cserje', location: 'mindkettő', price: 9900, sale_price: null, stock: 13, light: 'direkt nap', watering: 'közepes', difficulty: 'haladó', current_height_cm: 50, max_height_cm: 200, current_pot_cm: 21, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.4, reviews_count: 67, description: 'Illatos virágú, termő dézsás citrusfa napos, védett helyre.' },
  { name: 'Puszpáng', latin_name: 'Buxus sempervirens', category: 'kerti', location: 'kültéri', price: 3800, sale_price: null, stock: 24, light: 'közepes', watering: 'közepes', difficulty: 'haladó', current_height_cm: 30, max_height_cm: 200, current_pot_cm: 17, pet_safe: false, kid_safe: true, air_purifying: false, rating: 4.2, reviews_count: 39, description: 'Sűrű, formázható örökzöld sövény- és szegélynövény.' },
  { name: 'Gumifikusz', latin_name: 'Ficus elastica', category: 'szobanövény', location: 'beltéri', price: 5500, sale_price: null, stock: 21, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 60, max_height_cm: 250, current_pot_cm: 17, pet_safe: false, kid_safe: true, air_purifying: true, rating: 4.5, reviews_count: 104, description: 'Fényes, bőrszerű levelű, mutatós és könnyen tartható szobafa.' },
  { name: 'Kínai pénzfa', latin_name: 'Pilea peperomioides', category: 'szobanövény', location: 'beltéri', price: 2900, sale_price: null, stock: 32, light: 'közepes', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 18, max_height_cm: 30, current_pot_cm: 11, pet_safe: true, kid_safe: true, air_purifying: false, rating: 4.7, reviews_count: 129, description: 'Kerek, érme alakú levelek; könnyen szaporítható, állatbarát kedvenc.' },
  { name: 'Szobafenyő', latin_name: 'Araucaria heterophylla', category: 'szobanövény', location: 'beltéri', price: 7200, sale_price: null, stock: 8, light: 'erős', watering: 'közepes', difficulty: 'kezdő', current_height_cm: 50, max_height_cm: 200, current_pot_cm: 17, pet_safe: true, kid_safe: true, air_purifying: true, rating: 4.3, reviews_count: 45, description: 'Örökzöld, fenyőszerű szobanövény, télen élő karácsonyfa-alternatíva.' },
]
